version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secure-file-upload-app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./uploads:/usr/src/app/uploads 
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      DATABASE_URL: "postgresql://${DB_USER:-app_user}:${DB_PASSWORD:-app_password}@db:5432/${DB_NAME:-app_db}?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME:-3600s}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      UPLOAD_DEST: /usr/src/app/uploads
      MAX_FILE_SIZE_BYTES: ${MAX_FILE_SIZE_BYTES:-10485760}
      FILE_PROCESSING_QUEUE_NAME: ${FILE_PROCESSING_QUEUE_NAME:-file-processing-queue}
      PROCESS_FILE_JOB_NAME: ${PROCESS_FILE_JOB_NAME:-process-file-job}

      DB_USER: ${DB_USER:-app_user}
      DB_PASSWORD: ${DB_PASSWORD:-app_password}
      DB_NAME: ${DB_NAME:-app_db}

    depends_on:
      redis:
        condition: service_healthy
      db: 
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Waiting for services to be ready...'
        # Ensure PostgreSQL is ready (healthcheck in 'db' service helps)
        
        if [ \"$${NODE_ENV}\" = \"production\" ]; then
          echo 'Running Prisma migrations for production...'
          npx prisma migrate deploy;
        else
          echo 'Running Prisma migrations for development...'
          # The '--name docker_init' will be created on first run
          # '--skip-generate' assumes prisma client is generated during Docker build
          npx prisma migrate dev --name docker_postgres_init --skip-generate;
        fi &&
        
        echo 'Running Prisma database seed...'
        npx prisma db seed &&
        
        echo 'Starting application...'
        node dist/main.js
      "

  redis:
    image: redis:7-alpine
    container_name: secure-file-upload-redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: secure-file-upload-postgres\
    environment:
      POSTGRES_USER: ${DB_USER:-app_user} 
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app_password}
      POSTGRES_DB: ${DB_NAME:-app_db} 
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-app_user} -d $${POSTGRES_DB:-app_db} -q"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

 
volumes:
  redis-data: {}
  postgres-data: {}

networks:
  app-network:
    driver: bridge